### ISSUE TITLE
U2F notification does not work

### ISSUE THREAD

**Issue by myelsukov** [maximbaz/yubikey-touch-detector#10] opened 2020-04-13 20:26 UTC
Hi Maxim, you may remember me from other threads :)

Unfortunatelly, U2F notification does not work for me. GPG notifications work fine though.
I opened three terminals

Terminal1:
```
> sudo ls
Downloads            Desktop                   Documents
```

Terminal2:
```
> inotifywait -m /dev/hidraw5 /dev/hidraw6 /run/user/1000/pam-u2f-authpending
Setting up watches.
Watches established.
/run/user/1000/pam-u2f-authpending OPEN 
/dev/hidraw5 OPEN 
/dev/hidraw5 CLOSE_WRITE,CLOSE 
/dev/hidraw6 OPEN 
/dev/hidraw6 CLOSE_WRITE,CLOSE 
/dev/hidraw6 OPEN 
/dev/hidraw6 MODIFY 
/dev/hidraw6 ACCESS 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 ACCESS 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 ACCESS 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 ACCESS 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 ACCESS 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 MODIFY 
/dev/hidraw6 ACCESS 
/dev/hidraw6 ACCESS 
/dev/hidraw6 CLOSE_WRITE,CLOSE 
/run/user/1000/pam-u2f-authpending CLOSE_NOWRITE,CLOSE 
```

Terminal3:
```
> yubikey-touch-detector -v
DEBU[2020-04-13T13:15:53-07:00] Starting YubiKey touch detector              
DEBU[2020-04-13T13:15:53-07:00] SSH watcher is successfully established      
DEBU[2020-04-13T13:15:53-07:00] GPG watcher is successfully established      
DEBU[2020-04-13T13:15:53-07:00] U2F watcher on '/dev' is successfully established 
```

Do you have any means to increase verbosity of the debug output?
What additional information about my environment do you need?

**Comment by maximbaz** [comment] 2020-04-13 21:48
Hey! Judging by your output, the app doesn't detect the hidraw device that is yubikey, i.e. this line is never executed: 

https://github.com/maximbaz/yubikey-touch-detector/blob/d840f71994ee16f483ae78294db92d6149f9aa37/detector/u2f.go#L71

a simple test, keep terminal 3 with running app, unplug and plug yubikey and see if a new debug log appears and if detection will suddenly start to work. 

if yes, we will look into why initial detection is not working for you, maybe that sleep(1s) is too low and I need to increase it.

**Comment by myelsukov** [comment] 2020-04-13 21:51
I already tried that after reading the code :) Nothing happened.

**Comment by maximbaz** [comment] 2020-04-13 21:53
hmmm I think we should try to increase the sleep in that function nevertheless - I'm on a phone already, I will give you a modified binary tomorrow, unless you can change the code and compile one yourself 🙂

**Comment by maximbaz** [comment] 2020-04-13 21:54
This line: 

https://github.com/maximbaz/yubikey-touch-detector/blob/d840f71994ee16f483ae78294db92d6149f9aa37/detector/u2f.go#L55

**Comment by myelsukov** [comment] 2020-04-13 21:54
Never tried to `go` :)

**Comment by maximbaz** [comment] 2020-04-13 21:56
no worries, will ping you tomorrow and we will get to the bottom of it 👍 thanks for reporting btw!

**Comment by myelsukov** [comment] 2020-04-13 21:56
Thanks!

**Comment by myelsukov** [comment] 2020-04-13 22:01
I just tried `go run ./main.go` and it worked :) 
May be I will try to play with it.

**Comment by maximbaz** [comment] 2020-04-13 22:02
you can also just run make and it will compile you a binary 🙂

**Comment by myelsukov** [comment] 2020-04-13 22:03
I am going to print debugging stuff here and there.

**Comment by maximbaz** [comment] 2020-04-14 08:58
Good morning, the binary with `5s` sleep and some extra debugging logs: 
[sleep-5s.tar.gz](https://github.com/maximbaz/yubikey-touch-detector/files/4474240/sleep-5s.tar.gz)



Besides many "doesn't contain hidraw" lines, what you are expected to see is this:

```
DEBU[2020-04-14T10:55:56+02:00] checkAndInitWatcher: sleeping 5s             
DEBU[2020-04-14T10:56:01+02:00] U2F watcher on '/dev/hidraw0' is successfully established 
DEBU[2020-04-14T10:56:01+02:00] checkAndInitWatcher: established watch on '/dev/hidraw0' !!! 
DEBU[2020-04-14T10:56:01+02:00] checkAndInitWatcher: sleeping 5s             
DEBU[2020-04-14T10:56:06+02:00] checkAndInitWatcher: file '/sys/class/hidraw/hidraw1/device/uevent' doesn't contain string 'YubiKey' 
DEBU[2020-04-14T10:56:06+02:00] checkAndInitWatcher: sleeping 5s             
DEBU[2020-04-14T10:56:11+02:00] checkAndInitWatcher: file '/sys/class/hidraw/hidraw2/device/uevent' doesn't contain string 'YubiKey' 
```

This tells us that there are three `hidraw` devices (0, 1, 2), and only `0` was recognized as yubikey.

Let me know what you see 🙂 If none are recognized as yubikey, please `cat` the `/sys/class/hidraw/hidrawN/device/uevent` (for all hidraw devices)

**Comment by myelsukov** [comment] 2020-04-14 15:38
Thanks!

```
DEBU[2020-04-14T08:35:11-07:00] checkAndInitWatcher: file '/sys/class/hidraw/hidraw5/device/uevent' doesn't contain string 'YubiKey' 
DEBU[2020-04-14T08:35:11-07:00] checkAndInitWatcher: sleeping 5s             
DEBU[2020-04-14T08:35:16-07:00] checkAndInitWatcher: file '/sys/class/hidraw/hidraw6/device/uevent' doesn't contain string 'YubiKey' 
D
```

```
> cat /sys/class/hidraw/hidraw{5,6}/device/uevent
DRIVER=hid-generic
HID_ID=0003:00001050:00000407
HID_NAME=Yubico Yubikey 4 OTP+U2F+CCID
HID_PHYS=usb-0000:00:14.0-5/input0
HID_UNIQ=
MODALIAS=hid:b0003g0001v00001050p00000407
DRIVER=hid-generic
HID_ID=0003:00001050:00000407
HID_NAME=Yubico Yubikey 4 OTP+U2F+CCID
HID_PHYS=usb-0000:00:14.0-5/input1
HID_UNIQ=
MODALIAS=hid:b0003g0001v00001050p00000407
```

**Comment by maximbaz** [comment] 2020-04-14 15:40
Nice catch with lowercase search 🤔

**Comment by maximbaz** [comment] 2020-04-14 15:43
Could you please verify that it's working with this binary? [lowercase.tar.gz](https://github.com/maximbaz/yubikey-touch-detector/files/4476270/lowercase.tar.gz)

**Comment by myelsukov** [comment] 2020-04-14 15:45
Yes, it does!
```
> ./yubikey-touch-detector -v
DEBU[2020-04-14T08:44:31-07:00] Starting YubiKey touch detector              
DEBU[2020-04-14T08:44:31-07:00] SSH watcher is successfully established      
DEBU[2020-04-14T08:44:31-07:00] U2F watcher on '/dev' is successfully established 
DEBU[2020-04-14T08:44:31-07:00] GPG watcher is successfully established      
DEBU[2020-04-14T08:44:37-07:00] U2F watcher on '/dev/hidraw5' is successfully established 
DEBU[2020-04-14T08:44:38-07:00] U2F watcher on '/dev/hidraw6' is successfully established 
DEBU[2020-04-14T08:44:49-07:00] [notifiers/stdout] U2F_0                     
DEBU[2020-04-14T08:44:49-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-14T08:44:49-07:00] [notifiers/stdout] U2F_0                     
DEBU[2020-04-14T08:44:49-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-14T08:44:49-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-14T08:44:55-07:00] [notifiers/stdout] U2F_0                     
```

**Comment by maximbaz** [comment] 2020-04-14 15:49
Awesome! Interesting that you have two hidraw devices that contain "yubikey", I have only one - probably because I disabled OTP... 🤔 

Just out of curiosity, if you run watch for two devices in separate terminals, does only one of them trigger open/close events or both? `inotifywait -m -e open -e close /dev/hidrawN`

**Comment by myelsukov** [comment] 2020-04-14 15:50
I think it's one per slot, but I may be mistaken.

**Comment by myelsukov** [comment] 2020-04-14 15:52
Do you think you should listen on just one of them? U2F functionality is device-wide, not the slot specific. A slot can be configured as OTP, Challenge/Response or Static password.

**Comment by myelsukov** [comment] 2020-04-14 15:55
I missed your request: `sudo ls? inotifywait -m -e open -e close /dev/hidrawN` You can see it in the snippet at the very top. It actually touches both of them.

**Comment by maximbaz** [comment] 2020-04-14 15:57
Right, I see now... I'm just worried that this can lead to false positives (when app will say yubikey waits for a touch because of U2F but in fact you are using OTP slot), or the other way around (the app will say that yubikey is no longer waiting for a touch, but in fact it does, but your OTP slot generated a "close" event).

But I don't know how to distinguish the two devices, and which one to listen... 🤔

**Comment by maximbaz** [comment] 2020-04-14 15:59
Judging by your snippet above, the devices are touched in order (sequence is preserved, open -> close -> open -> close), but I'm not sure if this is guaranteed. Can you trick yubikey-touch-detector by showing false signal, if you e.g. do `sudo ls`, don't touch device, and then use OTP ?

**Comment by maximbaz** [comment] 2020-04-14 16:01
I wouldn't worry about "flapping" signals too much (e.g. if you get `U2F_1`, `U2F_0` and `U2F_1` again in one millisecond), but I worry that yubikey-touch-detector will remain in `U2F_1` for a long period of time (more than a few seconds) when it's not waiting for a touch, or if it will remain in `U2F_0` for more than a few seconds when in fact yubikey _is_ waiting for a touch.

**Comment by myelsukov** [comment] 2020-04-14 16:04
I don't have the OTP configured. It is just enabled. I used Challenge/Response before switching to the U2F. I may experiment with that later. That would require PAM configuration change and reboot. I am kinda busy now :)

I don't think you should differentiate U2F/OTP or Challenge/Response. In the long run, it is not important. You can log different triggers for bookkeeping, but you should have just one notification: "Please touch the key" :)

**Comment by maximbaz** [comment] 2020-04-14 16:07
True 🙂 

Thanks very much for your help, I'll push a fix for this bug, and if you spot weird behaviors later on, do let me know and we will tackle them separately!

**Comment by myelsukov** [comment] 2020-04-14 16:08
I think, it works like that:
1. They probe both inputs and decide which one to use
2. They open the chosen input and do ACCESS,MODIFY,MODIFY,MODIFY until user touches the key.
3. They close the input.

**Closed** 2020-04-14 16:12 UTC

**Comment by myelsukov** [comment] 2020-04-14 22:58
First run after upgrade to the newest version failed. Second attempt worked.

```
> yubikey-touch-detector -v
DEBU[2020-04-14T15:54:32-07:00] Starting YubiKey touch detector              
DEBU[2020-04-14T15:54:32-07:00] SSH watcher is successfully established      
fatal error: concurrent map writes

goroutine 10 [running]:
runtime.throw(0x5630c0c1c8ef, 0x15)
	runtime/panic.go:1116 +0x74 fp=0xc000058df8 sp=0xc000058dc8 pc=0x5630c0b249e4
runtime.mapassign_faststr(0x5630c0c6e960, 0xc000108810, 0x5630c0c1c623, 0x14, 0xc000108930)
	runtime/map_faststr.go:211 +0x3f9 fp=0xc000058e60 sp=0xc000058df8 pc=0x5630c0b04e19
github.com/maximbaz/yubikey-touch-detector/notifier.SetupUnixSocketNotifier(0xc000108810, 0xc0001087e0)
	github.com/maximbaz/yubikey-touch-detector/notifier/unix_socket.go:52 +0x3f7 fp=0xc000058fd0 sp=0xc000058e60 pc=0x5630c0c07037
runtime.goexit()
	runtime/asm_amd64.s:1373 +0x1 fp=0xc000058fd8 sp=0xc000058fd0 pc=0x5630c0b54551
created by main.main
	command-line-arguments/main.go:70 +0x630

goroutine 1 [chan receive]:
main.main()
	command-line-arguments/main.go:83 +0x74f

goroutine 6 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000742a0, 0xc0000741e0)
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:36 +0xb8
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:29 +0xde

goroutine 7 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000742a0, 0xc000074240)
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:81 +0x5a
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:30 +0x10a

goroutine 8 [runnable]:
os/signal.signal_enable(0x557696a000000002)
	runtime/sigqueue.go:219 +0x6e
os/signal.enableSignal(...)
	os/signal/signal_unix.go:51
os/signal.Notify.func2(0x2)
	os/signal/signal.go:150 +0x90
os/signal.Notify(0xc0001d0060, 0xc000059f48, 0x2, 0x2)
	os/signal/signal.go:162 +0x172
main.setupExitSignalWatch(0xc0001087e0)
	command-line-arguments/main.go:88 +0xb6
created by main.main
	command-line-arguments/main.go:66 +0x5d9

goroutine 9 [chan receive]:
github.com/maximbaz/yubikey-touch-detector/notifier.SetupStdErrNotifier(0xc000108810)
	github.com/maximbaz/yubikey-touch-detector/notifier/stderr.go:11 +0xac
created by main.main
	command-line-arguments/main.go:69 +0x604

goroutine 11 [chan receive]:
github.com/maximbaz/yubikey-touch-detector/detector.CheckGPGOnRequest(0xc0000201e0, 0xc000108810, 0xc00001e3f0, 0x21)
	github.com/maximbaz/yubikey-touch-detector/detector/gpg.go:53 +0x22e
created by main.main
	command-line-arguments/main.go:76 +0x699

goroutine 12 [semacquire]:
sync.runtime_SemacquireMutex(0xc000114034, 0x1, 0x1)
	runtime/sema.go:71 +0x49
sync.(*Mutex).lockSlow(0xc000114030)
	sync/mutex.go:138 +0xfe
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
github.com/sirupsen/logrus.(*MutexWrap).Lock(...)
	github.com/sirupsen/logrus@v1.4.2/logger.go:53
github.com/sirupsen/logrus.(*Entry).fireHooks(0xc0000a4150)
	github.com/sirupsen/logrus@v1.4.2/entry.go:244 +0x135
github.com/sirupsen/logrus.Entry.log(0xc000114000, 0xc0000a0060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/sirupsen/logrus@v1.4.2/entry.go:224 +0x116
github.com/sirupsen/logrus.(*Entry).Log(0xc0000a40e0, 0x5, 0xc00009adf0, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Entry).Logf(0xc0000a40e0, 0xc000000005, 0x5630c0c220a7, 0x2f, 0xc00009aec0, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.4.2/entry.go:314 +0xe4
github.com/sirupsen/logrus.(*Logger).Logf(0xc000114000, 0x5, 0x5630c0c220a7, 0x2f, 0xc00009aec0, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.4.2/logger.go:145 +0x96
github.com/sirupsen/logrus.(*Logger).Debugf(...)
	github.com/sirupsen/logrus@v1.4.2/logger.go:155
github.com/sirupsen/logrus.Debugf(...)
	github.com/sirupsen/logrus@v1.4.2/exported.go:144
github.com/maximbaz/yubikey-touch-detector/detector.WatchU2F.func1(0x5630c0c1920c, 0x4, 0xc000092000, 0x1, 0x1, 0x0)
	github.com/maximbaz/yubikey-touch-detector/detector/u2f.go:23 +0x220
github.com/maximbaz/yubikey-touch-detector/detector.WatchU2F(0xc000108810)
	github.com/maximbaz/yubikey-touch-detector/detector/u2f.go:66 +0x10c
created by main.main
	command-line-arguments/main.go:78 +0x6bb

goroutine 13 [runnable]:
strings.(*Builder).grow(...)
	strings/builder.go:68
strings.(*Builder).Grow(...)
	strings/builder.go:82
strings.ToUpper(0xc00021201b, 0x5, 0x5, 0x5)
	strings/strings.go:570 +0x224
github.com/sirupsen/logrus.(*TextFormatter).printColored(0xc00007e0f0, 0xc00021a1b0, 0xc00021e0e0, 0x5630c0dbbc88, 0x0, 0x0, 0xc0001298a8, 0x5630c0c1d90e, 0x19)
	github.com/sirupsen/logrus@v1.4.2/text_formatter.go:219 +0x80
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc00007e0f0, 0xc00021e0e0, 0xc000096c48, 0x5630c0bcf6bf, 0x5630c0c7fcc0, 0xc00021a1b0, 0xc000096c90)
	github.com/sirupsen/logrus@v1.4.2/text_formatter.go:177 +0xef9
github.com/sirupsen/logrus.(*Entry).write(0xc00021e0e0)
	github.com/sirupsen/logrus@v1.4.2/entry.go:255 +0x7e
github.com/sirupsen/logrus.Entry.log(0xc000114000, 0xc00021a180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/sirupsen/logrus@v1.4.2/entry.go:231 +0x1a0
github.com/sirupsen/logrus.(*Entry).Log(0xc00021e070, 0xc000000005, 0xc000096ed0, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Logger).Log(0xc000114000, 0xc000000005, 0xc000096ed0, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x7f
github.com/sirupsen/logrus.(*Logger).Debug(...)
	github.com/sirupsen/logrus@v1.4.2/logger.go:202
github.com/sirupsen/logrus.Debug(...)
	github.com/sirupsen/logrus@v1.4.2/exported.go:99
github.com/maximbaz/yubikey-touch-detector/detector.WatchGPG.func1()
	github.com/maximbaz/yubikey-touch-detector/detector/gpg.go:25 +0x1f9
github.com/maximbaz/yubikey-touch-detector/detector.WatchGPG(0xc00001e3f0, 0x21, 0xc0000201e0)
	github.com/maximbaz/yubikey-touch-detector/detector/gpg.go:28 +0xb4
created by main.main
	command-line-arguments/main.go:79 +0x6f3

goroutine 14 [IO wait]:
internal/poll.runtime_pollWait(0x7ff54475df78, 0x72, 0x0)
	runtime/netpoll.go:203 +0x57
internal/poll.(*pollDesc).wait(0xc000140098, 0x72, 0x0, 0x0, 0x5630c0c198dc)
	internal/poll/fd_poll_runtime.go:87 +0x47
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000140080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:384 +0x1d6
net.(*netFD).accept(0xc000140080, 0x5630c0b04db3, 0xd0, 0x5630c0c83800)
	net/fd_unix.go:238 +0x44
net.(*UnixListener).accept(0xc0001088d0, 0xc00012dde8, 0xc00012ddf0, 0x38)
	net/unixsock_posix.go:162 +0x34
net.(*UnixListener).Accept(0xc0001088d0, 0x5630c0c9eab8, 0xc0000202a0, 0x5630c0ca3aa0, 0xc0001088d0)
	net/unixsock.go:260 +0x66
github.com/maximbaz/yubikey-touch-detector/detector.WatchSSH(0xc0000201e0, 0xc0001087e0)
	github.com/maximbaz/yubikey-touch-detector/detector/ssh.go:67 +0x648
created by main.main
	command-line-arguments/main.go:80 +0x71f

goroutine 18 [runnable]:
os/signal.loop()
	os/signal/signal_unix.go:21
created by os/signal.Notify.func1
	os/signal/signal.go:127 +0x46

goroutine 34 [syscall]:
syscall.Syscall6(0xe8, 0xa, 0xc00004779c, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x1, 0x0, 0x0)
	syscall/asm_linux_amd64.s:41 +0x5
golang.org/x/sys/unix.EpollWait(0xa, 0xc00004779c, 0x1, 0x1, 0xffffffffffffffff, 0x5630c0c17030, 0x5630c0c9eac8, 0xc000090000)
	golang.org/x/sys@v0.0.0-20190712062909-fae7ac547cb7/unix/zsyscall_linux_amd64.go:1760 +0x74
github.com/rjeczalik/notify.(*inotify).loop(0xc000180000, 0xc0000a8000)
	github.com/rjeczalik/notify@v0.9.2/watcher_inotify.go:194 +0x79
created by github.com/rjeczalik/notify.(*inotify).lazyinit
	github.com/rjeczalik/notify@v0.9.2/watcher_inotify.go:134 +0x13f

goroutine 35 [runnable]:
github.com/rjeczalik/notify.(*inotify).send(0xc000180000, 0xc0000a8000)
	github.com/rjeczalik/notify@v0.9.2/watcher_inotify.go:253
created by github.com/rjeczalik/notify.(*inotify).lazyinit
	github.com/rjeczalik/notify@v0.9.2/watcher_inotify.go:137 +0x192

goroutine 36 [chan receive]:
github.com/rjeczalik/notify.(*inotify).send(0xc000180000, 0xc0000a8000)
	github.com/rjeczalik/notify@v0.9.2/watcher_inotify.go:254 +0xad
created by github.com/rjeczalik/notify.(*inotify).lazyinit
	github.com/rjeczalik/notify@v0.9.2/watcher_inotify.go:137 +0x192

goroutine 15 [chan receive]:
github.com/maximbaz/yubikey-touch-detector/detector.WatchSSH.func1(0xc0000202a0, 0x5630c0ca3aa0, 0xc0001088d0, 0xc00001e450, 0x2d, 0xc00001c1ce, 0x24)
	github.com/maximbaz/yubikey-touch-detector/detector/ssh.go:56 +0x3d
created by github.com/maximbaz/yubikey-touch-detector/detector.WatchSSH
	github.com/maximbaz/yubikey-touch-detector/detector/ssh.go:55 +0x590

goroutine 16 [runnable]:
github.com/maximbaz/yubikey-touch-detector/notifier.SetupUnixSocketNotifier.func1(0xc000020300, 0x5630c0ca3aa0, 0xc000108930)
	github.com/maximbaz/yubikey-touch-detector/notifier/unix_socket.go:43
created by github.com/maximbaz/yubikey-touch-detector/notifier.SetupUnixSocketNotifier
	github.com/maximbaz/yubikey-touch-detector/notifier/unix_socket.go:43 +0x39f
```

**Comment by myelsukov** [comment] 2020-04-14 23:04
Interesting behavior when HMAC Challenge/Response is requesting a touch:

```
 > yubikey-touch-detector -v
DEBU[2020-04-14T16:01:45-07:00] Starting YubiKey touch detector              
DEBU[2020-04-14T16:01:45-07:00] SSH watcher is successfully established      
DEBU[2020-04-14T16:01:45-07:00] U2F watcher on '/dev' is successfully established 
DEBU[2020-04-14T16:01:45-07:00] GPG watcher is successfully established      
DEBU[2020-04-14T16:01:51-07:00] U2F watcher on '/dev/hidraw5' is successfully established 
DEBU[2020-04-14T16:01:52-07:00] U2F watcher on '/dev/hidraw6' is successfully established 

# sudo ls is executed in the other terminal

DEBU[2020-04-14T16:02:09-07:00] U2F watcher on '/dev/hidraw5' is successfully established 
```

**Comment by maximbaz** [comment] 2020-04-15 06:51
I have seen that crash a couple of times, but haven't looked closely to what kind of concurrent map writes are causing it. It happened rare enough for me to ignore that problem 😁 

So when you use HMAC, device seems to disappear and reappear? 🤔

**Comment by myelsukov** [comment] 2020-04-15 16:26
> I have seen that crash a couple of times, but haven't looked closely to what kind of concurrent map writes are causing it. It happened rare enough for me to ignore that problem 

May be you could just wrap your main method in a try/catch block and restart the process if that specific error happens? That would be more friendly to the users who start the detector as a service.

> 
> So when you use HMAC, device seems to disappear and reappear?

This is what happens on a first `sudo` attempt:
```
/dev/hidraw5 ATTRIB 
/dev/hidraw5 DELETE_SELF 
```

All further `sudo` attempts do not generate any inotify notifications (but the key is blinking), so I think that you can't use inotify to detect requests for the key touch in the Challenge/Response case.

This experiment is not entirely clear, because I used C/R to login.

**Comment by maximbaz** [comment] 2020-04-15 16:33
> May be you could just wrap your main method in a try/catch block and restart the process if that specific error happens? That would be more friendly to the users who start the detector as a service.

I already fixed the issue, see the linked commit above 😉 Will be part of the next release!

> All further sudo attempts do not generate any inotify notifications (but the key is blinking), so I think that you can't use inotify to detect requests for the key touch in the Challenge/Response case.

Actually, I think I have an idea how we could capture HMAC! I think in your example, once yubikey starts waiting for a touch, /dev/hidraw5 is removed, but as soon as it stops waiting for a touch /dev/hidraw5 is re-appearing.

I will try to play and see if I can make something useful out of it, it might be challenging to distinguish this in code, but will try! :)

**Comment by myelsukov** [comment] 2020-04-15 16:37
I don't think it is easy to do.

1. The inotify events (see above) happen _after_ the touch.
2. They do happen only once. If I open a new terminal and try to use `sudo` again the key is blinking, but no new `inotify` events happen.

**Comment by maximbaz** [comment] 2020-04-15 16:39
I don't have a `sudo` setup, but here's how I reliably reproduce the indicator that I am thinking about:

```
$ ls -al /dev/hidraw*
(you will see N devices)

$ ykchalresp -v -2 test
(don't touch)

$ ls -al /dev/hidraw*
(you will see N-1 devices, less devices means it waits for a touch)

(touch)

$ ls -al /dev/hidraw*
(you will see N devices again, meaning it doesnt wait for a touch)
```

Tell me if you can reproduce this as well 🙂 Does the same approach work if you replace `ykchanresp` with `sudo`?

**Comment by maximbaz** [comment] 2020-04-15 16:42
> but no new inotify events happen.

I think once a file is removed (and later re-created), inotifywait "loses" it, and you must re-run it to get the next event

**Comment by myelsukov** [comment] 2020-04-15 16:45
You're right. I just did exactly this experiment and I restarted `inotifywait` in between.
It works the same way with `sudo` ( surprise! :grin: ):
1. Start blinking -> DELETE_SELF
2. Stop blinking -> device is recreated.

**Comment by maximbaz** [comment] 2020-04-15 16:46
Niiiice 🙂 If I manage to make something working, I will ping you (from #6) 🙂 Thanks for this idea!

**Comment by myelsukov** [comment] 2020-04-15 16:46
No problem!

**Comment by myelsukov** [comment] 2020-04-16 00:33
Please fix this line: https://github.com/maximbaz/yubikey-touch-detector/blob/master/notifier/libnotify.go#L21

**Comment by myelsukov** [comment] 2020-04-16 00:37
I would also suggest to make libnotify notification command customizable.
I have a nice script that also plays ping sound :grin: 
That would also solve localization problem.

**Comment by myelsukov** [comment] 2020-04-16 01:52
Actually whatever you call libnotify notification is actually a very distant relative to the libnotify :grin: 

I think you could find a neutral name for that. May be `--notification-command="foo bar"` with the same implementation as current `--libnotify`?

**Comment by myelsukov** [comment] 2020-04-16 06:53
Interesting observation.

My gnupg (smartcard) stuff is configured to be available **_without_** key touch.
Obviously, I have PINs set up.
Every time when gnupg asks for a PIN (pinentry is invoked) the yubikey-touch-detector treats it as a key touch request (even if it is not) and generates a notification.

It is not bad for me :grin: because I run a custom version of the yubikey-touch-detector which just generates a ping sound (pinentry with a sound is nice) , but it definitely can be confusing for other people.

**Comment by maximbaz** [comment] 2020-04-16 07:34
It was impossible to distinguish PIN and touch request, unfortunately... I also just learned to live with it. 

I'll have a look at notification later today, thanks 🙂

**Comment by maximbaz** [comment] 2020-04-16 08:58
> I would also suggest to make libnotify notification command customizable.
> I have a nice script that also plays ping sound 😁

Have you considered naming your script `notify-send`? 🙂 

To be honest I wouldn't want to extend this too much, custom command, custom title, custom message, icon, whatnot... I think if you want to customize the behavior, you should just subscribe on yubikey-touch-detector messages and implement your custom logic.

Have a look here: https://github.com/maximbaz/dotfiles/blob/master/bin/waybar-yubikey

You can have something very similar to listen on events and do anything you want, play sounds, change background color, etc 🙂

**Comment by myelsukov** [comment] 2020-04-16 15:29
> To be honest I wouldn't want to extend this too much

I totally understand. What about sane compromise? :grin: 
Before calling `notify-send` you would check if executable `$XDG_CONFIG_HOME/yubikey-touch-detector/notify-send` exists and run it instead of `notify-send`

**Comment by maximbaz** [comment] 2020-04-16 16:35
You can already do this like so 🙂 : `$ PATH="$XDG_CONFIG_HOME/yubikey-touch-detector:$PATH" yubikey-touch-detector -v`

**Comment by myelsukov** [comment] 2020-04-16 17:24
> You can already do this like so slightly_smiling_face : $ PATH="$XDG_CONFIG_HOME/yubikey-touch-detector:$PATH" yubikey-touch-detector -v

I don't mind if you would add it here: https://github.com/maximbaz/yubikey-touch-detector/blob/master/yubikey-touch-detector.service :grin: 

> If your own notify-send is an implementation that you want to use for all apps
I have `send-notify` script that can be used to send desktop notification on both FreeDesktop and Mac OS (A lot of my scripts are platform agnostic. I have a company-issued Mac Book Pro). The interface is a simplified version of the `notify-send` with possibility to add sound to the notification. It is definitely on the `PATH` but I would obviously hesitate to name it `notify-send` :grin: 

BTW, I have replaced `browserpass` with my own scripts. It is not as convenient as `browserpass` (separate call for each separate input field) but it works in any console or GUI application.
I have nice hotkeys: `<Caps Lock>P` for password, `<Caps Lock>L` for login name, `<Caps Lock>O` for OTP, etc.
I have couple of scripts that do that. And those scripts also run on Linux and Mac. I use my `pass` extension for that: https://github.com/myelsukov/field

**Comment by maximbaz** [comment] 2020-04-16 17:32
You can create an override for the systemd service that updates the PATH or command, but I think it's too specific to your use case to be added globally  sorry 🙂 As said libnotify implementation is not meant to be extensible, it's rather an example of a way of listening to the signals.

**Comment by maximbaz** [comment] 2020-04-16 17:35
For your pass scripts, consider also if you can make a shortcut that will not only type a single field, but will type one field, then TAB keypress and then another field - 99% of cases for username and password forms can be covered with username TAB password

**Comment by myelsukov** [comment] 2020-04-16 18:01
> You can create an override for the systemd service that updates the PATH or command

It's easier for me to fork your repo :grin: 

> For your pass scripts, consider also if you can make a shortcut that will not only type a single field, but will type one field, then TAB keypress and then another field - 99% of cases for username and password forms can be covered with username TAB password

Too dangerous. The password may land in the wrong place. I don't mind to press hotkey more than once per login. In many cases login and password are on the separate pages (we use Okta for authentication at work and it has separate screens for login, password and OTP).

I have specialized hotkeys for the logins that I use most often. Since when I use <Caps Lock> as Mod3, I have a lot of free hotkeys :)

**Comment by myelsukov** [comment] 2020-04-16 18:09
But you gave me good idea. I can terminate login name with a TAB. If I am lucky, then I should just press password hotkey after that. 

Thanks.

**Comment by maximbaz** [comment] 2020-04-20 22:55
@myelsukov would you be able to test U2F detection in this binary? It's a complete rewrite of U2F/FIDO2 support that doesn't depend on any file watcher hacks, but properly reading HID device according to the spec. Thanks!

[new-u2f.tar.gz](https://github.com/maximbaz/yubikey-touch-detector/files/4506663/new-u2f.tar.gz)

**Comment by myelsukov** [comment] 2020-04-20 23:00
I will.

**Comment by myelsukov** [comment] 2020-04-20 23:04
What specific tests do you want me to do?

**Comment by maximbaz** [comment] 2020-04-20 23:06
Maybe just run it with `-v` flag and see that (1) there are no errors and (2) U2F is actually being detected properly, e.g. if you use `sudo` commands, or on sites like https://webauthn.io

**Comment by myelsukov** [comment] 2020-04-20 23:07
Just did it. It sends me one notification per YubiKey blink :grin: Let me grab a log for you

**Comment by maximbaz** [comment] 2020-04-20 23:08
Yeeeees right, of course. That is expected though, but I again forgot about libnotify. I guess it's time to extend it a bit and make it stateful.

**Comment by myelsukov** [comment] 2020-04-20 23:09
```
./yubikey-touch-detector -v
DEBU[2020-04-20T16:08:18-07:00] Starting YubiKey touch detector              
DEBU[2020-04-20T16:08:18-07:00] SSH watcher is successfully established      
DEBU[2020-04-20T16:08:18-07:00] U2F watcher on '/dev' is successfully established 
DEBU[2020-04-20T16:08:18-07:00] HMAC watcher on '/dev' is successfully established 
DEBU[2020-04-20T16:08:18-07:00] GPG watcher is successfully established      
DEBU[2020-04-20T16:08:36-07:00] [notifiers/stdout] U2F_0                     
DEBU[2020-04-20T16:08:36-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:36-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:37-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:38-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:39-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:40-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:41-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:42-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:43-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:44-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:45-07:00] [notifiers/stdout] U2F_1                     
DEBU[2020-04-20T16:08:46-07:00] [notifiers/stdout] U2F_0                     
DEBU[2020-04-20T16:08:46-07:00] [notifiers/stdout] U2F_0                     
```

**Comment by maximbaz** [comment] 2020-04-20 23:30
Could you give this one a try? Should be fixed, also for HMAC as it was also prone for duplicate messages. 
[new-u2f.tar.gz](https://github.com/maximbaz/yubikey-touch-detector/files/4506801/new-u2f.tar.gz)

**Comment by myelsukov** [comment] 2020-04-20 23:39
I will try it

**Comment by myelsukov** [comment] 2020-04-20 23:46
Much better. I will keep it running.
