### ISSUE TITLE
No U2F events captured after boot

### ISSUE THREAD

**Issue by Majiir** [maximbaz/yubikey-touch-detector#48] opened 2023-10-06 21:51 UTC
I use the systemd user service to run yubikey-touch-detector. I'm using NixOS 23.05 with GNOME 44.2.

When I first boot my machine, no U2F events are captured. (I don't use any other watchers.) The logs indicate successful startup of the service:

```
time="2023-10-06T17:24:42-04:00" level=debug msg="Starting YubiKey touch detector"
time="2023-10-06T17:24:42-04:00" level=debug msg="No 'gpg' binary in $PATH or '/home/majiir/.gnupg/pubring.kbx' could not be found. Disabling GPG and SSH watchers."
time="2023-10-06T17:24:42-04:00" level=debug msg="U2F watcher on '/dev' is successfully established"
time="2023-10-06T17:24:42-04:00" level=debug msg="HMAC watcher on '/dev' is successfully established"
```

However, no events are recorded in the logs, sent to the unix socket, or notified through libnotify.

The issue can be fixed by restarting the service or by unplugging and replugging the Yubikey (which is already inserted when the machine boots). In the latter case, the logs simply start recording events as usual.

Is the service missing a dependency? I noticed that it doesn't require `dbus.socket`, but adding that didn't fix the issue. The issue seems to be related to the watchers.

**Comment by maximbaz** [comment] 2023-10-06 22:05
Another interesting issue! The U2F watcher depends on the presence of `/dev/hidraw*` devices, it's quite interesting that those are not present on your system yet, when the app launches.

This page has some diagrams of the order of systemd dependencies: https://man7.org/linux/man-pages/man7/bootup.7.html

I can't easily find the problem though, `default.target` seems to be executed quite late... Can you spot a possible dependency?

**Comment by maximbaz** [comment] 2024-11-21 20:01
Judging by https://github.com/NixOS/nixpkgs/issues/277119 this is no longer reproducible, thus closing.

**Closed by maximbaz** 2024-11-21 20:01 UTC
